list1=list(range(3,15))
print(list1)
print(min(list1))
print(min(list1,key=str))
words= "Papa u Vasi silyon v matematike".split()
print(words)
print(min(words))
print(min(words ,key=str.upper))
print(max(words,key=str.upper))
